dbfilename redis_queue.rdb
dir /home/frapee-pugal/my-frappe-site/config/pids
pidfile /home/frapee-pugal/my-frappe-site/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/frapee-pugal/my-frappe-site/config/redis_queue.acl
