; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:my-frappe-site-frappe-web]
command=/home/frapee-pugal/my-frappe-site/env/bin/gunicorn -b 127.0.0.1:8000 -w 5 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/web.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=frapee-pugal
directory=/home/frapee-pugal/my-frappe-site/sites
startretries=10

[program:my-frappe-site-frappe-schedule]
command=/home/frapee-pugal/.local/bin/bench schedule
priority=3
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/schedule.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/schedule.error.log
user=frapee-pugal
directory=/home/frapee-pugal/my-frappe-site
startretries=10



[program:my-frappe-site-frappe-short-worker]
command=/home/frapee-pugal/.local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/worker.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/worker.error.log
user=frapee-pugal
stopwaitsecs=360
directory=/home/frapee-pugal/my-frappe-site
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:my-frappe-site-frappe-long-worker]
command=/home/frapee-pugal/.local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/worker.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/worker.error.log
user=frapee-pugal
stopwaitsecs=1560
directory=/home/frapee-pugal/my-frappe-site
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10





[program:my-frappe-site-redis-cache]
command=/usr/bin/redis-server /home/frapee-pugal/my-frappe-site/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/redis-cache.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/redis-cache.error.log
user=frapee-pugal
directory=/home/frapee-pugal/my-frappe-site/sites
startretries=10

[program:my-frappe-site-redis-queue]
command=/usr/bin/redis-server /home/frapee-pugal/my-frappe-site/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/redis-queue.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/redis-queue.error.log
user=frapee-pugal
directory=/home/frapee-pugal/my-frappe-site/sites
startretries=10



[program:my-frappe-site-node-socketio]
command=/usr/bin/node /home/frapee-pugal/my-frappe-site/apps/frappe/socketio.js
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/frapee-pugal/my-frappe-site/logs/node-socketio.log
stderr_logfile=/home/frapee-pugal/my-frappe-site/logs/node-socketio.error.log
user=frapee-pugal
directory=/home/frapee-pugal/my-frappe-site
startretries=10


[group:my-frappe-site-web]
programs=my-frappe-site-frappe-web,my-frappe-site-node-socketio




[group:my-frappe-site-workers]
programs=my-frappe-site-frappe-schedule,my-frappe-site-frappe-short-worker,my-frappe-site-frappe-long-worker




[group:my-frappe-site-redis]
programs=my-frappe-site-redis-cache,my-frappe-site-redis-queue
